server:
  port: 8888

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Lihanwen123.

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jc.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true